/*************************************
Append labels to the merged and prepped data in stata
For version 2.0 of the data

Created by BG: June 29, 2017
**************************************/
clear
cap log close
pause on
set more off

/*set working directory*/
cap cd "/Users/benjamag/Google Drive/Master IPE Data/"

use "Graham_Tucker_IPE_v2_0_NoLabel", replace

/**************************
Append all the variable labels one at a time
These should match the .RDATA labels and the codebook
**************************/

*label var countryname_raw_EF "Original country Name in EF"
label var top_margintax_EF "Top marginal income tax rate [EF]"
label var top_margin_payrolltax_EF "Top marginal income and payroll tax rate [EF]"
label var propright_EF "Protection of property rights [EF]"
label var impartcourts_EF "Impartial courts [EF]"
label var bizcrimecost_EF "Business cost of crime [EF]"
label var policerely_EF "Reliability of police [EF]"


*label var countryname_raw_FH "Original country Name in FH"

label var pl_FH "Gastil index of political liberties [FH]"
label var cl_FH "Gastil index of civil liberties [FH]"
label var rulelaw_FH "Rule of Law Index [FH]"

*label var countryname_raw_TR "Original country Name in TR"
label var ers_TR  "Exchange Rate Stability Index [TR]"
label var mi_TR  "Monetary Independence Index [TR]"
label var ka_open_TR  "Financial Openness Index [TR]"

*label var countryname_raw_MC "Original country Name in MC"
label var cinc_MC  "CINC Score [MC]"
label var milex_MC  "Military Expenditures [MC]"
label var milper_MC  "Military Personnel  [MC]"
label var irst_MC  "Iron and steel production [MC]"
label var pec_MC  "Primary energy consumption [MC]"
label var tpop_MC  "Total Population [MC]"
label var upop_MC  "Urban population [MC]"

*label var countryname_raw_SI "Original country Name in SI"
label var milex_SI  "Military Expenditures (SIPRI) in millions (2011 USD) [SI]"

*label var countryname_raw_BH "Original country Name in BH"
label var cbi_BH  "Central bank Indepedence score [BH]"
label var cbiw_BH  "Weighted Central Bank Independence score [BH]"
label var reform_BH  "Reform year (yes/no) [BH]"


*label var countryname_raw_UNCTAD "Original country Name in UNCTAD"
label var fdiflows_UNCTAD "FDI Flows (Inward) USD Millions [UNCTAD]"
label var fdistocks_UNCTAD "FDI Stocks (Inward) USD Millions [UNCTAD]"

*label var countryname_raw_OFS "Original country Name in OFS"
label var ind_total_OFS "Outward FDI stocks from the US in USD (millions), all industries, BEA [OFS]"



*label var countryname_raw_OFI "Original country Name in OFI"
label var ind_total_OFI  "US Outward FDI: Position, All Industries, in mil. USD [OFI]" 
label var mining_OFI  "US Outward FDI: Position, Mining, in mil. USD [OFI]"
label var util_OFI  "US Outward FDI: Position, Utilities, in mil. USD [OFI]"
label var mf_total_OFI  "US Outward FDI: Position, Manufacturing: Total Manufacturing, in mil. USD [OFI]"
label var mf_food_OFI  "US Outward FDI: Position, Manufacturing: Food, in mil. USD [OFI]"
label var mf_chem_OFI  "US Outward FDI: Position, Manufacturing: Chemicals, in mil. USD [OFI]"
label var mf_pfm_OFI  "US Outward FDI: Position, Manufacturing: Primary and fabricated metals, in mil. USD [OFI]"
label var mf_mc_OFI   "US Outward FDI: Position, Manufacturing: Machinery, in mil. USD [OFI]"
label var mf_cep_OFI   "US Outward FDI: Position, Computers and electronic products, in mil. USD [OFI]"
label var mf_eeac_OFI  "US Outward FDI: Position, Electrical equipment, appliances, components, in mil. USD [OFI]"
label var mf_te_OFI  "US Outward FDI: Position, Manufacturing: Transportation Equipment, in mil. USD [OFI]"
label var mf_other_OFI   "US Outward FDI: Position, Manufacturing: Other Manufacturing, in mil. USD [OFI]"
label var wt_OFI  "US Outward FDI: Position, Wholesale Trade, in mil. USD [OFI]"
label var info_OFI  "US Outward FDI: Position, Information, in mil. USD [OFI]"
label var dep_ins_OFI  "US Outward FDI: Position, Depository Institutions, in mil. USD [OFI]"
label var fi_OFI   "US Outward FDI: Position, Finance (no depository inst.) and insurance, in mil. USD [OFI]"
label var psts_OFI  "US Outward FDI: Position, Professional, scientific, technical services, in mil. USD [OFI]"
label var hc_nb_OFI  "US Outward FDI: Position, Holding Companies (nonbank), in mil. USD [OFI]"
label var ind_other_OFI  "US Outward FDI: Position, Other Industries, in mil. USD [OFI]"

*label var countryname_raw_PW "Original country Name in PW"
label var currency_unit_PW  "Currency Unit [PW]"
label var rgdpe_PW  "Expenditure-side real GDP at chained PPPs (in mil. 2011US$) [PW]"
label var rgdpo_PW  "Output-side real GDP at chained PPPs (in mil. 2011US$) [PW]"
label var pop_PW  "Population (in millions) [PW]"
label var emp_PW  "Number of persons engaged (in millions) [PW]"
label var hc_PW  "Average annual hours worked by persons engaged [PW]"
label var cgdpe_PW  "Expenditure-side real GDP at current PPPs (in mil. 2011US$) [PW]"
label var cgdpo_PW  "Output-side real GDP at current PPPs (in mil. 2011US$) [PW]"
label var ck_PW  "Capital stock at current PPPs (in mil. 2011US$) [PW]"
label var ctfp_PW  "TFP level at current PPPs (USA=1) [PW]"
label var rgdpna_PW  "Real GDP at constant 2011 national prices (in mil. 2011US$) [PW]"
label var rkna_PW  "Capital stock at constant 2011 national prices (in mil. 2011US$) [PW]"
label var rtfpna_PW  "TFP at constant national prices (2011=1) [PW]"
label var rwtfpna_PW  "Welfare-relevant TFP at constant national prices (2011=1) [PW]"
label var labsh_PW  "Share of labor compensation in GDP at current national prices [PW]"
label var xr_PW  "Exchange rate, national currency/USD (market+estimated) [PW]"
label var statcap_PW  "Statistical capacity indicator (source: World Bank, developing countries only) [PW]"


label var p_FHP "Printing press freedom [FHP]"
label var b_FHP "Broadcast press freedom [FHP]"
label var ss_FHP "Free status [FHP]"
label var sr_FHP "Numerical score [FHP]"

*label var countryname_raw_WDI "Original country Name in WDI"
label var area_WDI "Surface area (sq.km) [WDI]"
label var area_land_WDI "Land area (sq.km) [WDI]"
label var armed_WDI "armed forces personnel, total [WDI]"
label var deaths_bt_WDI "Battle-related deaths(number of people) [WDI]"
label var debt_cgov_WDI "Central government debt. Total (% of GDP) [WDI]"
label var ex_agri_WDI " Agricultural raw materials exports (% of merchandise exports) [WDI]"
label var ex_food_WDI " Food exports (% of merchandise exports) [WDI]"
label var ex_fuel_WDI " Fuel exports (% of merchandise exports) [WDI]"
label var ex_mfg_WDI "Manufactures exports (% of merchandise exports) [WDI]"
label var ex_oresmet_WDI "Ores and metal exports (% of merchandise exports) [WDI]"
label var exp_WDI "Exports of goods and services (% of GDP) [WDI]"
label var extdebt_WDI "External debt stocks (% of GNI) [WDI]"
label var extdebt_avgint_WDI "Average interest on new external debt commitments (%) [WDI]"
label var extdebt_avgintoff_WDI "Average interest on new external debt commitments, official (%) [WDI]"
label var extdebt_avgintpriv_WDI "Average interest on new external debt commitments, private (%) [WDI]"
label var extdebt_intpaygni_WDI "Interest payments on external debt (% of GNI) [WDI]"
label var extdebt_intpayperex_WDI "Interest payments on external debt (% exports and primary income) [WDI]"
label var extdebt_pv_WDI "Present value of external debt (current US$) [WDI]"
label var extdebt_tot_WDI "External debt stocks, total (DOD, current US$) [WDI]"
label var fdidollars_WDI "Foreign direct investment, net inflows (BoP, current US$) [WDI]"
label var fdi_inper_WDI "Foreign direct investment, net inflows (% of GDP) [WDI]"
label var fdi_outper_WDI "Foreign direct investment, net outflows (% of GDP) [WDI]"
label var gdp_WDI "GDP (constant 2005 US$) [WDI]"
label var growth_WDI "GDP growth (annual %) [WDI]"
label var gdppc_WDI "GDP per capita (constant 2005 US$) [WDI]" 
label var gini_WDI "GINI index [WDI]"
label var gni_WDI "GNI (constant 2005 US$) [WDI]"
label var gnipc_WDI "GNI per capita (constant 2005 US$) [WDI]"
label var inf_mort_WDI "Mortality rate, infant (per 1000 live births) [WDI]"
label var inflation_WDI "Inflation, consumer prices (annual%) [WDI]"
label var insfin_svc_WDI "Insurance and financial services (% of commercial service exports) [WDI]"
label var internet_br_WDI "Fixed broadband Internet subscribers (per 100 people) [WDI]"
label var journal_WDI "Scientific and technical journal articles [WDI]"
label var legal_rt_WDI "Strength of legal rights index (0=weak to 12=strong) [WDI]"
label var lending_intrate_WDI "Lending interest rate (%) [WDI]"
label var life_exp_WDI "Life expectancy at birth, total (years) [WDI]"
label var lit_WDI "Literacy rate, adult total (% of people ages 15 and above) [WDI]"
label var migrant_per_WDI "International migrant stock (% of population) [WDI]"
label var migrant_tot_WDI "International migrant stock, total [WDI]"
label var mobile_WDI "Mobile cellular subscriptions (per 100 people) [WDI]"
label var patapps_WDI "Patent applications, residents [WDI]"
label var pop_WDI "Population, total [WDI]"
label var pop_den_WDI "Population density (ppl per sq km of land area) [WDI]"
label var pop_urb_WDI "Urban population (% of total) [WDI]"
label var workingpop_WDI "Population ages 15-64 (% of total)[WDI]"
label var power_out_WDI "Power outages in firms in a typical month (number) [WDI]"
label var portfolio_WDI "Portfolio equity, net inflows (BoP, current US$) [WDI]"
label var reer_WDI "Real effective exchange rate index (2010 = 100) [WDI]"
label var remittances_WDI "Personal remittances, received (% of GDP) [WDI]"
label var reserves_im_WDI "Total reserves in months of imports [WDI]"
label var reserves_tot_WDI "Total reserves (includes gold, current US$) [WDI]"
label var rir_WDI "Real interest rate (%) [WDI]"
label var risk_prem_WDI "Risk premium on lending (lending rate minus treasury bill rate, %) [WDI]"
label var tax_rev_WDI "Tax revenue (% of GDP) [WDI]"
label var tech_rnd_WDI "Technicians in R&D (per million people) [WDI]"
label var tele_WDI "Telephone lines (per 100 people) [WDI]"
label var trade_WDI "Trade (% of GDP) [WDI]"
label var trade_services_WDI "Trade in services (% of GDP) [WDI]"
label var trdmk_apps_WDI  "Trademark applications, total [WDI]"
label var natresource_rents_WDI "Total natural resources rents (% of GDP) [WDI]"
label var govt_consump_WDI  "General government final consumption expenditure (% of GDP) [WDI]"
label var GNI_growth_WDI "GNI per capita growth (annual %) [WDI]"
label var capform_WDI  "Gross fixed capital formation (% of GDP) [WDI]"
label var capformraw_WDI "Gross capital formation (constant 2010 US$) [WDI]"
label var govexp_edu_WDI "Government expenditure on education, total (% of GDP) [WDI]"
*laebl var govexp_edu_pexp_WDI "Expenditure on education as % of total government expenditure (%) [WDI]"
label var netoda_WDI  "Net official development assistance received (current US$) [WDI]"
label var pop0_14_WDI "Population ages 0-14 (% of total) [WDI]"


*label var countryname_raw_OECD "Original country Name in OECD"
label var ltint_OECD "Long-term interest rate [OECD], percentage"


*label var countryname_raw_ILO "Original country Name in ILO"
label var unitlaborcost_ILO  "Mean nominal hourly labour cost per employee (Local Currency) [ILO]"

*label var countryname_raw_LI "Original country Name in LI"
label var taxincentsum_LI  "Sum of six types of tax incentives [LI]"


*label var countryname_raw_BZ "Original country Name in BZ"
label var rank_BZ "Ease of Doing Business Rank [WB_Biz]"
label var rank_sb_BZ "Starting a Business Rank [WB_Biz]"
label var sb_proc_BZ "Starting a business, procedures (number) [WB_Biz]"
label var sb_time_BZ "Starting a business, time (days) [WB_Biz]"
label var sb_cost_BZ "Starting a business, cost (% of income percapita) [WB_Biz]"
label var sb_paid_BZ "Starting a business, paid in min. cap (% of income per capita) [WB_Biz]"
label var rank_cp_BZ "Dealing with Construction Permits Rank [WB_Biz]"
label var cp_proc_BZ "Dealing with Construction Permits, procedures (number) [WB_Biz]"
label var cp_time_BZ "Dealing with Construction Permits, time (days) [WB_Biz]"
label var cp_cost_BZ "Dealing with Construction Permits, cost (% of warehouse value) [WB_Biz]"
label var rank_ge_BZ "Getting Electricity Rank [WB_Biz]"
label var ge_proc_BZ "Getting Electricity, procedures (number) [WB_Biz]"
label var ge_time_BZ "Getting Electricity, time (days) [WB_Biz]"
label var ge_cost_BZ "Getting Electricity, cost (% of income per capita) [WB_Biz]"
label var rank_rp_BZ "Registering Property Rank [WB_Biz]"
label var rp_proc_BZ "Registering Property, procedures (number) [WB_Biz]"
label var rp_time_BZ "Registering Property, time (days) [WB_Biz]"
label var rp_cost_BZ "Registering Property, cost (% of property value) [WB_Biz]"
label var rank_gc_BZ "Getting Credit Rank [WB_Biz]"
label var gc_legal_BZ "Getting Credit, strength of legal rights index (0-12) [WB_Biz]"
label var gc_legal_old_BZ "Getting Credit, strength of legal rights index (0-10) old methodology [WB_Biz]"
label var gc_info_BZ "Getting Credit, depth of credit information index (0-8) [WB_Biz]"
label var gc_info_old_BZ "Getting Credit, depth of credit information index (0-6) old methodology [WB_Biz]"
label var gc_pub_BZ "Getting Credit, public registry coverage (% of adults) [WB_Biz]"
label var gc_priv_BZ "Getting Credit, private bureau coverage (% of adults) [WB_Biz]"
label var rank_pi_BZ "Protecting Minority Investors Rank [WB_Biz]"
label var pi_disc_BZ "Protecting Minority Investors, extent of disclosure index (0-10) [WB_Biz]"
label var pi_dl_BZ "Protecting Minority Investors, extent of director liability index (0-10) [WB_Biz]"
label var pi_shsu_BZ "Protecting Minority Investors, ease of shareholder suits index (0-10) [WB_Biz]"
label var pi_shsu_old_BZ "Protecting Minority Investors, ease of shareholder suits index (0-10) old methodology [WB_Biz]"
label var pi_ip_BZ "Protecting Minority Investors, strength of investor protection index (0-10) [WB_Biz]"
label var pi_ip_old_BZ "Protecting Minority Investors, strength of investor protection index (0-10) old methodology [WB_Biz]"
label var rank_pt_BZ "Paying Taxes Rank [WB_Biz]"
label var pt_pay_BZ "Paying Taxes, payments (number per year) [WB_Biz]"
label var pt_time_BZ "Paying Taxes, time (hours per year) [WB_Biz]"
label var pt_prof_BZ "Paying Taxes, profit tax (%) [WB_Biz]"
label var pt_lab_BZ "Paying Taxes, labor tax and contributions (%) [WB_Biz]"
label var pt_other_BZ "Paying Taxes, other taxes (%) [WB_Biz]"
label var pt_tot_BZ "Paying Taxes, total tax rate (% profit) [WB_Biz]"
label var rank_tr_BZ "Trading Across Borders Rank [WB_Biz]"
label var tr_exdo_old_BZ "Trading Across Borders, documents to export (number) old methodology [WB_Biz]"
label var tr_exti_old_BZ "Trading Across Borders, time to export (days) old methodology [WB_Biz]"
label var tr_exco_old_BZ "Trading Across Borders, cost to export (number) old methodology [WB_Biz]"
label var rank_tr_BZ "Trading Across Borders, cost to export (US$ per container) [WB_Biz]"
label var tr_imdo_BZ "Trading Across Borders, documents to import (number) [WB_Biz]"
label var tr_imti_old_BZ "Trading Across Borders, time to import (days) [WB_Biz]"
label var tr_imco_old_BZ "Trading Across Borders, cost to import (US$ per container) [WB_Biz]"
label var rank_ec_BZ "Enforcing Contracts Rank [WB_Biz]"
label var ec_time_BZ "Enforcing Contracts, time (days) [WB_Biz]"
label var ec_cost_BZ "Enforcing Contracts, cost (% of claim) [WB_Biz]"
label var rank_ri_BZ "Resolving Insolvency Rank [WB_Biz]"
label var ri_time_BZ "Resolving Insolvency, time (years) [WB_Biz]"
label var ri_cost_BZ "Resolving Insolvency, cost (% of estate) [WB_Biz]"
label var ri_out_BZ "Resolving Insolvency, outcome (0 as piecemeal sale and 1 as going concern) [WB_Biz]"
label var ri_reco_BZ "Resolving Insolvency, recovery rate (cents on the dollar) [WB_Biz]"


label var exselec_DD "Mode of executive election [DD]"
label var legselec_DD "Mode of legislative election [DD]"
label var closed_DD "Status of legislature [DD]"
label var dejure_DD "Legal status of parties [DD]"
label var defacto_DD "De facto existence of parties [DD]"
label var defacto2_DD "Existence of parties outside regime front [DD]" 
label var democracy_DD "Dummy variable for democracy [DD]"
label var regime_DD "Regime classification (parliamentary, mil dictatorship, etc.) [DD]"
label var ttd_DD "Dummy for transition to democracy [DD]"
label var tta_DD "Dummy for transition to dictatorship [DD]"



label var fragment_P4 "Polity fragmentation [P4]"
label var democ_P4 "Institutionalized democracy [P4]"
label var autoc_P4 "Institutionalized autocracy [P4]"
label var polity_P4 "Combined polity score [P4]"
label var polity2_P4 "Revised combined polity score [P4]"
label var durable_P4 "Regime durability [P4]"
label var xconst_P4 "Executive constraints [P4]"
label var parreg_P4 "Regulation of participation [P4]"
label var parcomp_P4 "Competitiveness of participation [P4]"
label var polcomp_P4 "Political competition [P4]"
label var change_P4 "Total change in polity value [P4]"
label var sf_P4 "State failure [P4]"
label var regtrans_P4 "Regime transition [P4]"

*label var countryname_raw_DE "Original country Name in DE"
label var democracy_share_DE  "System Level Democratic Share [DE]"
label var democracy_count_DE  "Count of Democracies in the System [DE]"
label var lndemsys_DE  "Count of Democracies in the System (logged) [DE]"

*label var countryname_raw_WGI "Original country Name in WGI"
label var VA_EST_WGI  "Voice and accountability, estimate  [WB WGI]"
label var PV_EST_WGI  "Political stability absence of violence, estimate [WB WGI]"
label var GE_EST_WGI  "Government effectiveness, estimate [WB WGI]"
label var GQ_EST_WGI  "Regulatory quality, estimate [WB WGI]"
label var RL_EST_WGI  "Rule of law, estimate [WB WGI]"
label var CC_EST_WGI  "Control of corruption, estimate [WB WGI]"

*label var countryname_raw_SFI "Original country Name in SFI"
label var sfi_SFI  "State fragility index [SFI]"
label var effect_SFI  "Effectiveness score [SFI]"
label var legit_SFI  "Legitimacy score [SFI]"
label var seceff_SFI  "Security effectiveness score [SFI]"
label var secleg_SFI  "Security legitimacy score [SFI]"
label var poleff_SFI  "Political effectiveness score [SFI]"
label var polleg_SFI  "Political legitimacy score [SFI]"
label var ecoeff_SFI  "Economic effectiveness score [SFI]]"
label var ecoleg_SFI  "Economic legitimacy score [SFI]"
label var soceff_SFI  "Social effectiveness score [SFI]"
label var socleg_SFI  "Social legitimacy score [SFI]"


*label var countryname_raw_SGI "Original country Name in SGI"
label var corrupprev_SGI  "Rule of Law: Corruption Prevention [SGI]" 

*label var countryname_raw_WJP "Original country Name in WJP"
label var civil_cf_WJP  "Civil conflict is effectively limited [WJP]" 
label var cj_crpt_WJP  "Civil justice is free of corruption [WJP]" 
label var cj_delay_WJP  "Civil justice is not subject to unreasonable delays [WJP]" 
label var adr_acces_WJP  "ADRs are accessible, impartial, and effective [WJP]" 
label var cj_disc_WJP  "Civil justice is free of discrimination [WJP]" 
label var cj_enfor_WJP  "Civil justice is effectively enforced [WJP]" 
label var crime_ctrl_WJP  "Crime is effectively controlled [WJP]" 
label var due_admin_WJP  "Due process is respected in administrative proceedings [WJP]" 
label var exec_crpt_WJP  "Executive branch officials do not use public office for private gain [WJP]" 
label var expr_comp_WJP  "The Government does not expropriate without adequate compensation [WJP]" 
label var gov_reg_WJP  "Government regulations are applied and enforced without improper influence [WJP]" 
label var judic_crpt_WJP  "Judicial branch officials do not use public office for private gain [WJP]" 
label var legis_crpt_WJP  "Legislative branch officials do not use public office for private gain [WJP]" 
label var milt_crpt_WJP  "Police and Military officials do not use public office for private gain [WJP]" 
label var ppl_cj_WJP  "People have access to affordable civil justice [WJP]" 


*label var countryname_raw_FP "Original country Name in FP"
label var Rank_FP  "Reporters without Borders Press Freedom Annual Ranking [FP]"
label var Score_FP  "Reporters with Borders Press Freedom Score [FP]"




*label var countryname_raw_TI "Original country Name in TI"
label var ti_cpi_TI  "Corruption perceptions index [TI]" 

*label var countryname_raw_PVE "Original country Name in PVE"
label var totint_PVE  "Sum of interstate MEPV magnitude scores for neighboring states [PVE]" 
label var totciv_PVE  "Sum of civil and ethnic MEPVs in neighboring states [PVE]" 
label var totalac_PVE  "Sum of all MEPVs in neighboring states [PVE]" 
label var nint_PVE  "Number of bordering states with international MEPVs [PVE]" 
label var nciv_PVE  "Number of bordering states with civil or ethnic MEPVs [PVE]" 
label var nac_PVE  "Number of bordering states with any MEPVs [PVE]" 
label var region_PVE  "Region [PVE]" 
label var nregion_PVE  "Number of states in region [PVE]" 
label var regint_PVE  "Sum of interstate MEPV magnitude scores in region [PVE]" 
label var regciv_PVE  " Sum of civil and ethnic MEPVs in region [PVE]" 
label var regac_PVE  "Sum of all MEPVs in region [PVE]" 
label var nrint_PVE  "Number of states in region with international MEPVs [PVE]" 
label var nrciv_PVE  "Number of states in region with civil or ethnic MEPVs [PVE]" 
label var nrac_PVE  "Number of states in region with any MEPVs [PVE]" 

label var totint_PVE  "Sum of interstate MEPV magnitude scores for neighboring states [PVE]" 
label var totciv_PVE  "Sum of civil and ethnic MEPVs in neighboring states [PVE]" 
label var totalac_PVE  "Sum of all MEPVs in neighboring states [PVE]" 
label var nint_PVE  "Number of bordering states with international MEPVs [PVE]" 
label var nciv_PVE  "Number of bordering states with civil or ethnic MEPVs [PVE]" 
label var nac_PVE  "Number of bordering states with any MEPVs [PVE]" 
label var region_PVE  "Region [PVE]" 
label var nregion_PVE  "Number of states in region [PVE]" 
label var regint_PVE  "Sum of interstate MEPV magnitude scores in region [PVE]" 
label var regciv_PVE  " Sum of civil and ethnic MEPVs in region [PVE]" 
label var regac_PVE  "Sum of all MEPVs in region [PVE]" 
label var nrint_PVE  "Number of states in region with international MEPVs [PVE]" 
label var nrciv_PVE  "Number of states in region with civil or ethnic MEPVs [PVE]" 
label var nrac_PVE  "Number of states in region with any MEPVs [PVE]" 

* error
*label var countryname_raw_PTS "Original country Name in PTS"
label var politterr_a_PTS  "Political Terror Scale based on Amnesty International [PTS]" 
label var politterr_HRW_PTS  "Political Terror Scale based on HRW [PTS]" 
label var politterr_s_PTS  "Political Terror Scale based on the US State Department [PTS]" 


*label var countryname_raw_SVS "Original country Name in SVS"
label var sociaviol_SVS  "societal violence scale (1-5 with 5 being highest) [SVS]"

* label var countryname_raw_PO "Original country Name in PO"
* label var id_PO  "Conflict identifier [PO]"
* label var sidea_PO  "identifies the country of SideA. Always the government side in an internal conflict [PO]"
* label var sidea2nd_PO  "Names of states supporting side A with troops [PO]"
* label var incomp_PO  "Dyad incompatibility [PO]"
* label var terr_PO  "Name of territory [PO]"
* label var intensity_PO  "Intensity level (minor armed conflicts and wars) [PO]"
* label var cumintensity_PO  "cumulative intensity [PO]"
* label var type_PO  "Conflict type [PO]"
* label var region_PO  "Region of location [PO]"


*label var countryname_raw_UBD "Original country Name in UBD"
label var BdLow_UBD "Low estimate of annual battle fatalities [UBD]"
label var BdHigh_UBD "High estimate of annual battle fatalities [UBD]"
label var BdBest_UBD "Best estimate of annual battle fatalities [UBD]"



label var onset2_AO  "2 years between onset variables coded [AO]"
label var onset3_AO  "3 years between onset variables coded [AO]"
label var onset4_AO  "4 years between onset variables coded [AO]"
label var onset5_AO  "5 years between onset variables coded [AO]"
label var onset6_AO  "6 years between onset variables coded [AO]"
label var onset7_AO  "7 years between onset variables coded [AO]"
label var onset8_AO  "8 years between onset variables coded [AO]"
label var onset9_AO  "9 years between onset variables coded [AO]"

*label var countryname_raw_WE "Original country Name in WE"
label var tgpm_WE  "Transparency in government policy making [WEF]"

*label var countryname_raw_MEM "Original country Name in MEM"
label var EUmem_MEM  "binary, 1 if member, 0 if not [EU]"
label var EUwhen_MEM  "year of accession [EU]"
label var WTOwhen_MEM  " year of accession [WTO]"
label var WTOmem_MEM  "binary, 1 if member, 0 if not [WTO]"
label var IMFwhen_MEM  " year of accession [IMF]"
label var IMFmem_MEM  "binary, 1 if member, 0 if not [IMF]"
label var NATOwhen_MEM  " year of accession [NATO]"
label var NATOmem_MEM  "binary, 1 if member, 0 if not [NATO]"
label var OECDwhen_MEM  "year of accession [OECD]"
label var OECDmem_MEM  "binary, 1 if member, 0 if not [OECD]"


*label var countryname_raw_PIS "Original country Name in PIS"
label var math_avg_PIS "Average mathematics scores [PIS]"
label var reading_avg_PIS "Average reading scores [PIS]"
label var science_avg_PIS "Average science scores [PIS]"

*label var countryname_raw_ES "Original country Name in ES"
label var ptratio_seced_ES  "Pupil-teacher ratio in secondary education (headcount basis) [ES]"

*label var countryname_raw_PV "Original country Name in PV"
label var intind_PV  "War of Independence, Magnitude [PV]" 
label var intviol_PV  "International Violence, Magnitude [PV]" 
label var intwar_PV  "International Warfare, Magnitude [PV]" 
label var civviol_PV  "Civil Violence, Magnitude [PV]" 
label var civwar_PV  "Civil War, Magnitude [PV]" 
label var ethviol_PV  "Ethnic violence, Magnitude [PV]" 
label var ethwar_PV  "Ethnic War, Magnitude [PV]" 
label var inttot_PV  "Total interstate MEPVS, Magnitude [PV]" 
label var civtot_PV  "Total civil and ethnic MEPVS, Magnitude [PV]" 
label var actotal_PV  "Total MEPVS, Magnitude [PV]" 
label var nborder_PV  "Number of states sharing a border [PV]" 

*label var countryname_raw_LANG "Original country Name in LANG"
label var lang1_LANG  "Language 1 [LANG]"
label var lang2_LANG  "Language 2 [LANG]"

*label var countryname_raw_CE "Original country Name in CE"
label var english_off_CE  " Distance from US (km between most populous cities) [CE]"
label var dist_US_CE  " Official Language of the Country is English [CE]"


label var inclusive_IDC "Inclusive powersharing [IDC]"
label var dispersive_IDC "Dispersive Powersharing  [IDC]"
label var constraining_IDC "Constraining Powersharing  [IDC]"
label var inclusive_imp_IDC " Inclusive with missing values imputed [IDC]"
label var dispersive_imp_IDC "Dispersive with missing values imputed [IDC]"
label var constraining_imp_IDC "Constraining with missing values imputed [IDC]"
label var inclusive_nm_IDC "Inclusive with missing values replaced as 0 [IDC]"
label var dispersive_nm_IDC " Dispersive with missing values replaced as 0 [IDC]"
label var constraining_nm_IDC "Constraining with missing values replaced as 0 [IDC]"
label var constsusp_IDC "Constitution Suspended  [IDC]"
label var treaty_IDC "Treaty serving in lieu of a constitution [IDC]"
label var martiallaw_binary_IDC "Martial Law [IDC]"
label var gcman_IDC "Grand Coalition (mandated) [IDC]"
label var gcimp_IDC "Grand Coalition (implemented) [IDC]"
label var unity_IDC "National Unity Government [IDC]"
label var gcseats1_IDC "Grand Coalition by Seats (Two largest parties in government) [IDC]"
label var gcseats2_IDC "Grand Coalition by Seats (Excess Party in Coalition) [IDC]"
label var gcseats3_IDC "Grand Coalition by Seats (Either gscseats1 or gcseats2 = 1) [IDC]"
label var gcnew_IDC "gcman or unity = 1 [IDC]"
label var partynoethnic_IDC "Ethnic Party Ban [IDC]"
label var mveto_IDC "Mutual Veto [IDC]"
label var resman_IDC "Reserved Executive Positions (Mandated) [IDC]"
label var resimp_IDC "Reserved Executive Positions (Implemented) [IDC]"
label var resseats_IDC "Reserved Seats (Mandated) [IDC]"
label var resseats2_IDC "Reserved Seats Binary (Mandated) [IDC]"
label var resseatsimp_IDC "Reserved Seats (Implemented) [IDC]"
label var relestablish_IDC "State Establishment of Religion [IDC]"
label var relestablish_binary_IDC "State Establisment of Religion [IDC]"
label var relrestrict_IDC "State Restriction of (minority) religions [IDC]"
label var relconstp_IDC "Religion Protected (Practice) [IDC]"
label var relconstd_IDC "Religion Protected (Discrimination) [IDC]"
label var stconst_IDC "Regional Constituencies in the Upper House [IDC]"
label var state_IDC "State/Provincial Governments Locally Elected [IDC]"
label var state_dummy1_IDC "state_dummy1_IDC [IDC]"
label var state_dummy2_IDC "state_dummy2_IDC [IDC]"
label var muni_IDC "Municipal Governments Locally Elected [IDC]"
label var subtax_IDC "Sub-National Tax Authority [IDC]"
label var subed_IDC "Subnational Education Authority [IDC]"
label var subpolice_IDC "Subnational Police Authority [IDC]"
label var auton_IDC  "Asymmetric Federalism [IDC]"
label var milleg_IDC "Military Legislator Ban [IDC]"
label var miman_IDC "Inclusive Military [IDC]"
label var mfound_IDC "Foundational Military [IDC]"
label var milparty_IDC "Constitutional Provision Against Military Party Membership [IDC]"
label var milparty2_IDC "Mandatory Party Membership for Military [IDC]"
label var jtenure_IDC "Judicial Tenure [IDC]"
label var jtenure_dummy1_IDC "jtenure_dummy1_IDC [IDC]"
label var jtenure_dummy2_IDC "jtenure_dummy2_IDC [IDC]"
label var jcause_IDC "Judges can be removed without cause [IDC]"
label var japptbr_IDC "Judicial Appointment Authority Divided [IDC]"
label var jconst_IDC "Judicial Constitution [IDC]"
label var jrevman_IDC "Judicial Review [IDC]"
label var violation_IDC "Violation of Mandated Powersharing [IDC]"
label var pr_IDC "Proportional Representation [IDC]"

label var foreignbkct_CV "Count of foreign banks open in country [CV]"
*label var countryname_raw_CV "Country name used in raw data"

label var cim_CIM "Contract intensive money [IMF_IFS]"
label var cim_adj_CIM "Contract intensive money adjusted [IMF_IFS]"
*laebl var countryname_raw_CIM "Country name used in raw data [IMF_IFS]"


label var under_BCG "Whether a country was is under an IMF agreement [BCG]"
label var undertype_BCG "Type of IMF agreement country is under [BCG]"

label var pcredb_FS "Private credit by deposit money banks (% GDP) [FS]"
label var pcredbo_FS "Private credit by money banks and other financial institutions (% GDP) [FS]"
*label var countryname_raw_FS "country name used in raw data" 

label var class_5way_LY "5-way classification [LY&S]"
label var class_3way_LY "3-way classification [LY&S]"
*label var countryname_raw_LY "Country name used in raw data"

label var baselinemwp_LX "News coverage (total articles) [GKJ]"
label var investmentmwp_LX "Investment Articles in LexisNexis (keyword)[GKJ]"
label var subjectmwp_LX "Potentially Business Relevant Articles in LexisNexis (subjects) [GKJ]"
label var ln_baselinemwp_LX "Total Articles in LexisNexis (logged) [GKJ]"
label var ln_investmentmwp_LX "Investment Articles in LexisNexis (keyword) (logged)[GKJ]"
label var ln_subjectmwp_LX "Potentially Business Relevant Articles in LexisNexis (subjects) (logged)"
*label var countryname_raw_LX " Country name used in raw data"
  
label var news_WB "Daily newspapers (per 1,000 people) [WB2010]"
*label var countryname_raw_WB2010 "Country name used in raw data"



label var reportcount_IB "Number of Unique I/B/E/S Analyst Reports (IB)"
label var firmcount_IB "Number of Unique Firms Covered in I/B/E/S Analyst Reports (IB)"
label var analystcount_IB "Number of Unique I/B/E/S Analysts (IB)"
label var lnreportcount_IB "Number of Unique I/B/E/S Analyst Reports (logged) (IB)"
label var lnfirmcount_IB "Number of Unique Firms Covered in I/B/E/S Analyst Reports (logged) (IB)"              
label var lnanalystcount_IB "Number of Unique I/B/E/S Analysts (logged) (IB)"     

label var surges_FW "Capital Surge Episodes [FW]"
label var stops_FW "Capital Stop Episodes [FW]"
label var retrench_FW "Capital Retrenchment Episodes [FW]"
label var flight_FW "Capital Flight Episodes [FW]"         


label var net_ppe_OPE "US Outward FDI flows: Net Property, Plant, and Equipment in mil. USD [OPE]"

label var taxhavwhen_TH "Year estimate of when the state became a tax haven [DOT]"
label var taxhav_TH "Binary, 1 if considered a tax haven, 0 if not [DOT]"
label var taxhavens_extrapolated_TH "Binary, 1 if considered a tax haven, 0 if not. Extrapolated from taxhav [DOT]"
         

label var combinedoil_AE "Oil Exports (% of GDP) (Ashford) [AE]"



label var frmlacct_GFD "Account at a formal financial institution (% age 15+) [GFD]"
label var bk_acct_GFD  "Bank accounts per 1,000 adults [GFD]"
label var bk_branch_GFD  "Bank branches per 100,000 adults [GFD]"
label var finconst_GFD  "Firms identifying access to finance as a major constraint (%) [GFD]"
label var firms_bf_GFD  "Firms using banks to finance investments (%) [GFD]"
label var firms_bw_GFD "Firms using banks to finance working capital (%) [GFD]"
label var firms_loc_GFD  "Firms with a bank loan or line of credit (%) [GFD]"
label var firms_chksv_GFD  "Firms with a checking or savings account (%) [GFD]"
label var loancollat_GFD  "Value of collateral needed for a loan (% of the loan amount) [GFD]"
label var wc_bfin_GFD  "Working capital financed by banks (%) [GFD]"
label var fd_gdp_GFD  "Financial system deposits to GDP (%) [GFD]"
label var dc_priv_GFD  "Domestic credit to private sector (% of GDP) [GFD]"
label var bkconc_GFD  "Bank concentration (%) [GFD]"
label var bkcrisis_GFD  "Banking crisis dummy (1=banking crisis, 0=none) [GFD]"
label var depos_gdp_GFD  "Bank deposits to GDP (%) [GFD]"
label var forbnkast_GFD  "Foreign bank assets among total bank assets (%) [GFD]"
label var forbnk_GFD  "Foreign banks among total banks (%) [GFD]"
label var h_stat_GFD  "H-statistic for efficiency measures [GFD]"
label var nr_loan_GFD  "Loans from nonresident banks (amounts outstanding) to GDP (%) [GFD]"
label var fb_cons_GFD "Consolidated foreign claims of BIS reporting banks to GDP (%) [GFD]"
label var gpd_liab_GFD  "Gross portfolio debt liabilities to GDP (%) [GFD]"
label var gpe_liab_GFD  "Gross portfolio equity liabilities to GDP (%) [GFD]"
label var marketcap_GFD  "Stock market capitalization to GDP (%) [GFD]"
label var compratio_GFD  "Number of listed companies per 1,000,000 people [GFD]"
label var stockvol_GFD  "Stock price volatility [GFD]"


label var MFNtariff_MFN "MFN Applied Tariff Rate (unweighted %) [MFN]"
label var iMFN_tariff_MFN "MFN Applied Tariff Rate Interpolated [MFN]"


label var v2x_polyarchy_VDEM "Electoral democracy index [VDEM]"
label var v2x_api_VDEM "Additive polyarchy index [VDEM]"
label var v2x_mpi_VDEM "Multiplicative polyarchy index [VDEM]"
label var v2x_EDcomp_thick_VDEM "Electoral component index [VDEM]"
label var v2x_libdem_VDEM "Liberal democracy index [VDEM]"
label var v2x_liberal_VDEM "Liberal component index [VDEM]"
label var v2x_partipdem_VDEM "Participatory democracy index [VDEM]"
label var v2x_partip_VDEM "Participatory component index [VDEM]"
label var v2x_delibdem_VDEM "Deliberative democracy index [VDEM]"
label var v2xdl_delib_VDEM "Deliberative component index [VDEM]"
label var v2x_egaldem_VDEM "Egalitarian democracy index [VDEM]"
label var v2x_egal_VDEM "Egalitarian component index [VDEM]"
label var v2x_frassoc_thick_VDEM "Freedom of association (thick) index [VDEM]"
label var v2x_freexp_thick_VDEM "Expanded freedom of expression index [VDEM]"
label var v2x_freexp_VDEM "Freedom of expression index [VDEM]"
label var v2xme_altinf_VDEM "Alternative sources of information index [VDEM]"
label var v2x_suffr_VDEM "Share of population with suffrage [VDEM]"
label var v2xel_frefair_VDEM "Clean elections index [VDEM]"
label var v2x_accex_VDEM "Elected executive index [VDEM]"
label var v2xcl_rol_VDEM "Equality before the law and individual liberty index [VDEM]"
label var v2x_jucon_VDEM "Judicial constraints on the executive index [VDEM]"
label var v2xlg_legcon_VDEM "Legislative constraints on the executive index [VDEM]"
label var v2x_cspart_VDEM "Civil society participation index [VDEM]"
label var v2xdd_dd_VDEM "Direct popular vote index [VDEM]"
label var v2xel_locelec_VDEM "Local government index [VDEM]"
label var v2xel_regelec_VDEM "Regional government index [VDEM]"
label var v2xeg_eqprotec_VDEM "Equal protection index [VDEM]"
label var v2xeg_eqdr_VDEM "Equal distribution of resources index [VDEM]"
label var v2xcs_ccsi_VDEM "Core civil society index [VDEM]"
label var v2xps_party_VDEM "Party system institutionalization index [VDEM]"
label var v2x_gender_VDEM "Women political empowerment index [VDEM]"
label var v2x_gencl_VDEM "Women civil liberties index [VDEM]"
label var v2x_gencs_VDEM "Women civil society participation index [VDEM]"
label var v2x_genpp_VDEM "Women political participation index [VDEM]"
label var v2x_elecreg_VDEM "Electoral regime index [VDEM]"
label var v2xex_elecreg_VDEM "Executive electoral regime index [VDEM]"
label var v2xlg_elecreg_VDEM "Legislative electoral regime index [VDEM]"
label var v2xel_elecparl_VDEM "Legislative or constituent assembly election [VDEM]"
label var v2xlg_leginter_VDEM "Legislature closed down or aborted [VDEM]"
label var v2xel_elecpres_VDEM "Presidential election [VDEM]"
label var v2x_hosinter_VDEM "Chief executive no longer elected [VDEM]"
label var v2x_corr_VDEM "Political corruption [VDEM]"
label var v2x_pubcorr_VDEM "Public sector corruption index [VDEM]"
label var v2x_execorr_VDEM "Executive corruption index [VDEM]"
label var v2x_lgdivparctrl_VDEM "Divided party control of legislature [VDEM]"
label var v2x_feduni_VDEM "Division of power index [VDEM]"
label var v2x_civlib_VDEM "Civil liberties index [VDEM]"
label var v2x_clphy_VDEM "Physical violence index [VDEM]"
label var v2x_clpol_VDEM "Political liberties index [VDEM]"
label var v2x_clpriv_VDEM "Private liberties index [VDEM]"
label var v2elsrgel_VDEM "Regional Government Elected [VDEM]"
label var v2elreggov_VDEM "Regional Government Exists [VDEM]"
label var v2cltrnslw_VDEM "Transparent laws with predictable enforcement [VDEM]"
label var v2juhcind_VDEM  "High court independence [VDEM]"
label var v2juhccomp_VDEM "Government compliance with high court [VDEM]"
label var v2jureview_VDEM "Judicial review [VDEM]"

label var system_DPI "Political System [DPI]"
label var yrsoffc_DPI "Chief Executive Years in Office [DPI]"
label var finittrm_DPI "Finite Term in Office [DPI]"
label var yrcurnt_DPI "Years Left in Current Term [DPI]"             
label var multpl_DPI "Can Chief Executive Serve Multiple Terms [DPI]"
label var military_DPI "Is Chief Executive a Military Officer? [DPI]"                
label var defmin_DPI "Is Defense Minister a Military Officer? [DPI]"               
label var percent1_DPI "President Percentage of Votes, first round [DPI]"            
label var percentl_DPI "President Percentage of Votes, last round [DPI]"              
label var prtyin_DPI "Party of Chief Executive Length of Time in Office [DPI]"            
label var execme_DPI  "Name of Executive Party [DPI]"          
label var execrlc_DPI "Chief Executive Party Orientation [DPI]"              
label var execnat_DPI "Chief Executive Party: Nationalist [DPI]"
label var execrurl_DPI "Chief Executive Party: Rural [DPI]"             
label var execreg_DPI "Chief Executive Party: Regional [DPI]"           
label var execrel_DPI "Chief Executive Party: Religious [DPI]"         
label var execage_DPI "Age of Chief Executive Party [DPI]"
label var allhouse_DPI  "Does Party of Executive Control All Houses? [DPI]"          
label var nonchief_DPI "Party affiliation of Non-Chief Exec in Systems with Pres & PM [DPI]"            
label var totalseats_DPI "Total Seats in Legislature [DPI]"              
label var gov1me_DPI "Name of Largest Government Party [DPI]"            
label var gov1seat_DPI "Number of Seats of Largest Government Party [DPI]"           
label var gov1vote_DPI "Vote Share of Largest Government Party [DPI]"
label var gov1rlc_DPI "Largest Government Party Orientation [DPI]"
label var gov1nat_DPI "Largest Government Party: Nationalist [DPI]"
label var gov1rurl_DPI "Largest Government Party: Rural [DPI]"
label var gov1reg_DPI "Largest Government Party: Regional [DPI]"
label var gov1rel_DPI "Largest Government Party: Religious [DPI]"
label var gov1age_DPI " Age of Largest Government Party [DPI]"
label var gov2me_DPI "Name of 2nd Largest Government Party [DPI]"
label var gov2seat_DPI "Number of Seats of 2nd Largest Government Party [DPI]"
label var gov2vote_DPI "Vote Share of 2nd Largest Government Party [DPI]"
label var gov2rlc_DPI  "2nd Largest Government Party Orientation [DPI]"
label var gov2nat_DPI  "2nd Largest Government Party: Nationalist [DPI]"
label var gov2rurl_DPI  "2nd Largest Government Party: Rural [DPI]"
label var gov2reg_DPI  "2nd Largest Government Party: Regional [DPI]"
label var gov2rel_DPI  "2nd Largest Government Party: Religious [DPI]"
label var gov2age_DPI   "Age of 2nd Largest Government Party [DPI]"
label var gov3me_DPI   "Name of 3rd Largest Government Party [DPI]"
label var gov3seat_DPI  "Number of Seats of 3rd Largest Government Party [DPI]"
label var gov3vote_DPI   "Vote Share of 3rd Largest Government Party [DPI]"
label var gov3rlc_DPI  "3rd Largest Government Party Orientation [DPI]"
label var gov3nat_DPI  "3rd Largest Government Party: Nationalist [DPI]"
label var gov3rurl_DPI  "3rd Largest Government Party: Rural [DPI]"
label var gov3reg_DPI "3rd Largest Government Party: Regional [DPI]"
label var gov3rel_DPI "3rd Largest Government Party: Religious [DPI]"
label var gov3age_DPI "Age of 3rd Largest Government Party [DPI]"
label var govoth_DPI  "Number of Other Government Parties [DPI]"
label var govothst_DPI  "Number of Seats of Other Government Parties [DPI]"
label var govothvt_DPI  "Vote Share of Other Government Parties [DPI]"
label var opp1me_DPI   "Name of Largest Opposition Party [DPI]"
label var opp1seat_DPI   "Number of Seats of Largest Opposition Party [DPI]"
label var opp1vote_DPI  "Vote Share of Largest Opposition Party [DPI]"
label var opp1rlc_DPI  "Largest Opposition Party Orientation [DPI]"
label var opp1nat_DPI "Largest Opposition Party: Nationalist [DPI]"
label var opp1rurl_DPI "Largest Opposition Party: Rural [DPI]"
label var opp1reg_DPI  "Largest Opposition Party: Regional [DPI]"
label var opp1rel_DPI  "Largest Opposition Party: Religious [DPI]"
label var opp1age_DPI "Age of Largest Opposition Party [DPI]"
label var opp2me_DPI  " Name of 2nd Largest Opposition Party [DPI]"
label var opp2seat_DPI  "Number of Seats of 2nd Largest Opposition Party [DPI]"
label var opp2vote_DPI  "Vote Share of 2nd Largest Opposition Party [DPI]"
label var opp3me_DPI  "Name of 3rd Largest Opposition Party [DPI]"
label var opp3seat_DPI  "Number of Seats of 3rd Largest Opposition Party [DPI]"
label var opp3vote_DPI  "Vote Share of 3rd Largest Opposition Party [DPI]"
label var oppoth_DPI  "Number of Other Opposition Parties [DPI]"
label var oppothst_DPI "Number of Seats of Other Opposition Parties [DPI]"
label var oppothvt_DPI  "Number of Votes of Other Opposition Parties [DPI]"
label var ulprty_DPI "Number of Non-Aligned Parties [DPI]"
label var numul_DPI "Number of Seats of Non-Aligned Parties [DPI]"     
label var ulvote_DPI "Vote Share of Non-Aligned Parties [DPI]"  
label var oppmajh_DPI "Does One Opposition Party have a Majority in the House? [DPI]"   
label var oppmajs_DPI "Does One Opposition Party have a Majority in the Senate? [DPI]"
label var dateleg_DPI "Month Legislative Elections Held [DPI]"            
label var dateexec_DPI "Month Presidential Elections Held [DPI]"          
label var legelec_DPI "Legislative Election Held [DPI]"       
label var exelec_DPI "Presidential Election Held [DPI]"    
label var liec_DPI "Legislative Electoral Competitiveness [DPI]"            
label var eiec_DPI "Executive Electoral Competitiveness [DPI]"
label var mdmh_DPI "Mean District Magnitude House [DPI]"
label var mdms_DPI "Mean District Magnitude Senate [DPI]"
label var ssh_DPI "Number of Seats in Senate/Total Seats in Both Houses [DPI]"
label var plurality_DPI "Plurality [DPI]"
label var pr_DPI "Proportional Representation [DPI]"              
label var housesys_DPI "Electoral Rule House [DPI]"               
label var sensys_DPI "Electoral Rule Senate [DPI]"
label var thresh_DPI "Vote Threshold [DPI]"  
label var dhondt_DPI "D'Hondt System [DPI]"
label var cl_DPI "Closed List [DPI]"                  
label var select_DPI "Candidate Selection [DPI]"
label var fraud_DPI "Vote Fraud [DPI]"
label var auton_DPI "Autonomous Regions [DPI]"                  
label var muni_DPI "Municipal Government [DPI]"               
label var state_DPI "State Government [DPI]" 
label var author_DPI "State Government Authority over Taxing, Spending, or Legislating [DPI]"
label var stconst_DPI "Are the Constituencies of the Senators the States/Provinces? [DPI]"                
label var numgov_DPI "Number of Government Seats [DPI]"             
label var numvote_DPI "Vote Share of Government Parties [DPI]"    
label var numopp_DPI "Number of Opposition Seats [DPI]"
label var oppvote_DPI "Vote Share of Opposition Parties [DPI]"    
label var maj_DPI "Margin of Majority [DPI]"
label var partyage_DPI "Average Age of Parties [DPI]"   
label var herfgov_DPI "Herfindahl Index of Government Parties [DPI]" 
label var herfopp_DPI "Herfindahl Index of Opposition Parties [DPI]"
label var herftot_DPI "Herfindahl Index Total [DPI]"
label var frac_DPI "Fractionalization Index [DPI]"
label var oppfrac_DPI "Opposition Fractionalization Index [DPI]"
label var govfrac_DPI "Government Fractionalization Index [DPI]"
label var tensys_strict_DPI "tensys_strict [DPI]"
label var tensys_DPI "System Tenure [DPI]"
label var checks_lax_DPI "checks_lax [DPI]"
label var checks_DPI "Checks and Balances [DPI]"
label var stabs_strict_DPI "Stability (Threshold: LIEC = 6) [DPI]"
label var stabs_DPI "Stability [DPI]"        
label var stabns_strict_DPI "Stability, single chamber (Threshold: LIEC = 6) [DPI]" 
label var stabns_DPI "Stability, single chamber [DPI]"     
label var tenlong_strict_DPI "Longest Tenure of a Veto Player (Threshold: LIEC = 6) [DPI]"
label var tenlong_DPI "Longest Tenure of a Veto Player [DPI]"     
label var tenshort_strict_DPI "Shortest Tenure of a Veto Player (Threshold: LIEC = 6) [DPI]" 
label var tenshort_DPI "Shortest Tenure of a Veto Player [DPI]"    
label var polariz_DPI "Polarization [DPI]"

label var spell_GE "Time invariant count of number of years in power [Geddes]"
label var duration_GE "Time at risk of failure at time t [Geddes]"         
label var fail_GE "Binary variable indicating regime failure (fail==1) [Geddes]"       
label var fail_subsregime_GE "Regime failure, transition to [Geddes]"
label var fail_type_GE "Regime failure, type (howend) [Geddes]"       
label var fail_violent_GE "Regime failure, violence [Geddes]"
label var regimetype_GE "Regime type, including hybrids (10) [Geddes]"             
label var party_GE "Party regime (including hybrids, oligarchy, and Iran) [Geddes]"            
label var personal_GE "Personalist regime [Geddes]"
label var military_GE "Military regime (including milpersonal and indirect military) [Geddes]"            
label var monarch_GE "Monarchy [Geddes]"
          

label var democracy_BX "Democracy [Boix]"
label var sovereign_BX "Sovereign Dummy [Boix]"
label var democracy_trans_BX "Democratic Transition [Boix]"
label var democracy_breakdowns_BX "Democratic Breakdowns [Boix]"
label var democracy_duration_BX "Democratic Duration [Boix]"
label var democracy_omitteddata_BX "Democracy Omitted Data [Boix]"









label var lji_LS "Latent Judicial Independence Measure [LS]"

label var index_labor1_JCB "Level of worker protection through labor and employment laws. 0.77-2.31. [JCB]"
label var pright_JCB "Index of political rights in 1996 (1-7). [JCB]"
label var avelf_JCB "Avg. val. of five indices of ethnolinguistic fractionalization (0-5). [JCB]"
label var legor_uk_JCB "Origin of Company Law/Commercial Code is the English Common Law. [JCB]"
label var legor_fr_JCB "Origin of Company Law/Commercial Code is the French Commercial Code. [JCB]"
label var legor_so_JCB "Origin of Company Law/Commercial Code is the German Commercial Code. [JCB]"
label var legor_ge_JCB "Origin of Company Law/Commercial Code is the Scandinavian Commercial Code. [JCB]"
label var legor_sc_JCB "Origin of Company Law/Commercial Code is Socialist/Communist laws. [JCB]"
label var lat_abst_JCB "Absolute val. of the latitude of the country, values scaled 0-1. [JCB]"
label var f_prop97_JCB "Rating of property rights in each country in 1997 (1-5). [JCB]"
label var caselaw_JCB "Dummy variable. 1 if judicial decisions are a source of law, 0 otherwise. [JCB]"
label var sc_ten_JCB "Tenure of Supreme Court judges (0-2). [JCB]"
label var ac_ten_JCB "Tenure of highest ranked judges ruling on administrative cases. 0-2. [JCB]"
label var jud_rev_JCB "Extent, judges have power to review the constitutionality of laws. 0-2. [JCB]"
label var P_dem94_JCB "Democracy score in 1994 (0-10). Lower score ,less democracy. [JCB]"
label var lgdp_98_JCB "Logarithm of GDP/cap. in 1998 (USD). 4.5-10.5 in the sample. [JCB]"
label var rigid_JCB "How hard it is to change the constitution in a given country. (1-4). [JCB]"
label var humana_9_JCB "Based on three major UN treaties. Higher scores, better human rights. [JCB]"
label var proc_99_JCB "Number of procedures for a start-up to obtain a legal status (2-19). [JCB]"
label var gb_per_JCB "Share of assets of top 10 banks owned by the government in 1995. [JCB]"
label var new_constitutional_JCB "Sum of: judiciary review ind., rigidity of const. ind. [JCB]"
label var new_independence_JCB "Sum of: tenure of Sup. Ct. judges, admin. Ct. judges, case law ipe$. [JCB]"



label var prty_rights_BTI "Extent of government ensuring private property rights and regulations [BTI]"
label var edu_rd_BTI "Successfulness of education policies and government support for R & D [BTI]"

label var pr_rbgovn_IDA "Measure of Property Rights and Rule Based Governance [IDA]"


label var physint_CR "physical integrity rights index [CIRI]"
label var disap_CR "disappearnace [CIRI]" 
label var kill_CR "extrajudicial killing [CIRI]"
label var polpris_CR "political imprisonment [CIRI]"
label var tort_CR "torture [CIRI]"
label var assn_CR "freedom of assembly and association [CIRI]"
label var formov_CR "freedom of foreign movement [CIRI]"
label var dommov_CR "freedom of domestic movement [CIRI]"
label var old_move_CR "freedom of movement before 2007 [CIRI]"     
label var speech_CR "freedom of speech [CIRI]"
label var elecsd_CR "electoral self-determination [CIRI]"
label var old_relfre_CR "freedom of religion before 2007 [CIRI]"
label var new_relfre_CR "freedom of religion from 2007 [CIRI]"  
label var worker_CR "worker's rights [CIRI]"    
label var wecon_CR "women's economic rights [CIRI]"
label var wopol_CR "women's political rights [CIRI]"
label var wosoc_CR "women's social rights [CIRI]"   
label var injud_CR "independence of the judiciary [CIRI]"    
   


label var amnesty_FA "5 category [FA]"
label var state_FA "5 category [FA]"
label var hathaway_FA "5 category, ordered variable for torture [FA]"
label var itt_FA "6 category, ordered variable for torture [FA]"
label var genocide_FA "a binary variable for genocide [FA]"
label var ciri_FA "CIRI country identifier [FA]"
label var disap_FA "3 category, ordered variable for disappearances [FA]"
label var kill_FA "3 category, ordered variable from extra-judical killing [FA]"
label var polpris_FA "3 category, ordered variable for political imprisonment [FA]"
label var tort_FA "3 category, ordered variable for torture [FA]"
label var rummel_FA "a binary variable for politicide/genocide [FA]"
label var massive_repression_FA "a binary variable for massive repressive events [FA]"
label var executions_FA "a binary variable on executions [FA]"
label var killing_FA "binary version of one sided violence count data [FA]"
label var additive_FA "the CIRI Physint scale [FA]"
label var latentmean_FA "the posterior mean of the latent variable (i.e. human rights protection) [FA]"
label var latentsd_FA "the standard deviation of the posterior estimates for human rights protection [FA]"


label var laborrights_MU "Mosley-Uno measure of collective labor rights [MU]"

label var transparencyindex_HR "Transparency Index [HRV]"
label var transparencyindexub_HR "The estimated upper bound of the HRV index for each country and year [HRV]"
label var transparencyindexlb_HR "The estimated lower bound of the HRV index for each country and year [HRV]"
label var transparencyindexsd_HR "The standard deviation of 'HRV index' for each country and year [HRV]"  
label var transdiff_HR "The estimated one year change in HRV index for each country and year [HRV]"    
label var transdifflb_HR "The estimated lower bound of a one year change in the HRV index [HRV]"    
label var transdiffub_HR "The estimated upper bound of a one year change in the HRV index [HRV]"
  

label var MID_phat_MP "MID Propensity [NOR]"

label var peacekeep_PF "Whether the state hosted a UN Peacekeeping mission that year [PF]"
 
label var bdeadlow_BD "Low estimate of annual battle fatalities [BD]"
label var bdeadhigh_BD "High estimate of annual battle fatalities [BD]"
label var bdeadbest_BD "Best estimate of annual battle fatalities [BD]"

label var ipp_index_IP "International patent protection index [Park]"

label var ippstrength_ZH "IPP, 1 for weak 2 for strong [Zhao]"

label var bitstodate_BIT "BITs signed to date [BIT]"
label var lnbitstodate_BIT "BITs signed to date (logged) [BIT]"             
 
label var lh_1519_BL "Percentage of Tertiary Ages 15 to 19 [BL]"        
label var lh_2024_BL "Percentage of Tertiary Ages 20 to 24 [BL]"    
label var lh_25999_BL "Percentage of Tertiary Ages 25 and up [BL]"    
label var lh_F_1519_BL "Percentage of Tertiary Females Ages 15 to 19 [BL]"
label var lh_F_2024_BL "Percentage of Tertiary Females Ages 20 to 24 [BL]"     
label var lh_F_25999_BL "Percentage of Tertiary Females Ages 25 and up [BL]" 
label var lh_F_long_BL "Percentage of tertiary, female population aged 15-64 [BL]" 
label var lh_long_BL "Percentage of tertiary, population aged 15-64 [BL]"     
label var lpc_1519_BL "Percentage of Primary Complete Ages 15 to 19 [BL]"  
label var lpc_25999_BL "Percentage of Primary Complete Ages 25 and up [BL]"
label var lpc_F_1519_BL "Percentage of Primary Complete Females Ages 15 to 19 [BL]"
label var lpc_F_25999_BL "Percentage of Primary Complete Females Ages 25 and up [BL]"
label var ls_1519_BL "Percentage of Secondary Ages 15 to 19 [BL]"
label var ls_25999_BL "Percentage of Secondary Ages 25 and up [BL]"
label var ls_F_1519_BL "Percentage of Secondary Females Ages 15 to 19 [BL]"
label var ls_F_25999_BL "Percentage of Secondary Females Ages 25 and up [BL]"
label var ls_F_long_BL "Percentage of secondary, female population aged 15-64 [BL]"
label var ls_long_BL "Percentage of secondary, population aged 15-64 [BL]"
label var lsc_1519_BL "Percentage of Secondary Complete Ages 15 to 19 [BL]"
label var lsc_2024_BL "Percentage of Secondary Complete Ages 20 to 24 [BL]"
label var lsc_25999_BL "Percentage of Secondary Complete Ages 25 and up [BL]"
label var lsc_F_1519_BL "Percentage of Secondary Complete Females Ages 15 to 19 [BL]"
label var lsc_F_2024_BL "Percentage of Secondary Complete Females Ages 20 to 24 [BL]"
label var lsc_F_25999_BL "Percentage of Secondary Complete Females Ages 25 and up [BL]"
label var lu_1519_BL "Percentage of No Schooling Ages 15 to 19 [BL]"
label var lu_25999_BL "Percentage of No Schooling Ages 25 and up [BL]"
label var lu_F_1519_BL "Percentage of No Schooling Females Ages 15 to 19 [BL]"
label var lu_F_25999_BL "Percentage of No Schooling Females Ages 25 and up [BL]"
label var lu_F_long_BL "Percentage of no schooling, female population aged 15-64 [BL]"
label var lu_long_BL "Percentage of no schooling, population aged 15-64 [BL]"
label var pri_F_long_BL "Primary adjusted enrollment ratio (%) for female population [BL]"
label var pri_long_BL "Primary adjusted enrollment ratio (%) total population [BL]"
label var sec_F_long_BL "Secondary adjusted enrollment ratio (%) for female population [BL]"
label var sec_long_BL "Secondary adjusted enrollment ratio (%) total population [BL]"
label var syr_F_long_BL "Secondary years of schooling, female population ages 15-64 [BL]"
label var syr_long_BL "Secondary years of schooling, population ages 15-64 [BL]"
label var tyr_F_long_BL "Total years of schooling, female population ages 15-64 [BL]"
label var tyr_long_BL "Total years of schooling, population ages 15-64 [BL]"
label var yr_sch_1519_BL "Years of Schooling Ages 15 to 19 [BL]"
label var yr_sch_25999_BL "Years of Schooling Ages 25 and up [BL]"
label var yr_sch_F_1519_BL "Years of Schooling Females Ages 15 to 19 [BL]"
label var yr_sch_F_25999_BL  "Years of Schooling Females Ages 25 and up [BL]"
label var yr_sch_sec_1519_BL "Years of Secondary Schooling Ages 15 to 19 [BL]"
label var yr_sch_sec_25999_BL  "Years of Secondary Schooling Ages 25 and up [BL]"
label var yr_sch_sec_F_1519_BL "Years of Secondary Schooling Females Ages 15 to 19 [BL]"
label var yr_sch_sec_F_25999_BL "Years of Secondary Schooling Females Ages 25 and up [BL]"


 
label var egip_groups_count_EP "Number of EGIP groups [EP]"
label var excl_groups_count_EP "Number of MEG groups [EP]"
label var regaut_groups_count_EP "Number of groups with regional autonomy [EP]"
label var regaut_excl_groups_count_EP "Number of MEG groups with regional autonomy [EP]"
label var regaut_egip_groups_count_EP "Number of EGIP groups with regional autonomy [EP]"
label var rlvt_groups_count_EP "Number of relevant groups [EP]"
label var actv_groups_count_EP "Number of active groups [EP]"
label var lpop_EP "Sum of ethnically relevant population as fraction of total population [EP]"
label var egippop_EP "Sum of the population of all EGIP groups as fraction of total population [EP]"
label var legippop_EP "EGIP population as a fraction of ethnically relevant population [EP]"
label var exclpop_EP "Sum of the population of all MEG groups as fraction of total population [EP]"
label var lexclpop_EP "MEG population as a fraction of ethnically relevant population [EP]"
label var discrimpop_EP "Sum of discriminated population as fraction of total population [EP]"
label var ldiscrimpop_EP "Sum discriminated population as fraction of ethnically relevant population [EP]"
label var maxexclpop_EP "Size of largest MEG group as fraction of total population [EP]"
label var lmaxexclpop_EP "Size of largest MEG group as fraction of ethnically relevant population [EP]"
label var regautpop_EP "Sum of population with regional autonomy as fraction of total population [EP]"
label var regautexclpop_EP "Sum pop. with regional autonomy and excluded MEG as fraction of total pop. [EP]"
label var regautegippop_EP "Sum pop. with regional autonomy and included EGIP as fraction of total pop. [EP]"
label var cntr_relevance_EP "Is ethnicity relevant at least once in sample period (0=No, 1=Yes) [EP]"

label var burg_count_ODC "Burglary breaking and entering at the national level, number of police recorded offenses [ODC]"
label var burg_rate_ODC "Burglary breaking and entering at the national level, number of police recorded offenses per 10,000 of population [ODC]"
label var homicide_count_ODC "Intentional homicides [ODC]"
label var homicide_rate_ODC "Intentional homicides per 10,000 of population [ODC]"
label var housebrk_count_ODC "Housebreaking at the national level, number of police recorded offences [ODC]"
label var housebrk_rate_ODC "Housebreaking at the national level, number of police recorded offences per 10,000 of population [ODC]"
label var mvtheft_count_ODC "Motor Vehicle Theft at the national level, number of police-recorded offences [ODC]"
label var mvtheft_rate_ODC "Motor Vehicle Theft at the national level, number of police-recorded offences per 10,000 of population [ODC]"
label var robbery_count_ODC "Robbery at the national level, number of police-recorded offences [ODC]"
label var robbery_rate_ODC "Robbery at the national level, number of police-recorded offences per 10,000 of population [ODC]"
label var hommicidempc_count_ODC "Intentional homicide count in the most populated city [ODC]"
label var hommicidempc_rate_ODC "Intentional homicide rate per 10,000 of population in the most populated city [ODC]"
label var mpcity_ODC "The most populated city in each country [ODC]"
label var theft_count_ODC "Theft at the national level, number of police-recorded offences [ODC]"
label var theft_rate_ODC "Theft at the national level, number of police-recorded offences per 10,000 of population [ODC]"
label var theftcars_count_ODC "Theft of Private Cars, number of police recorded offences [ODC]"
label var theftcars_rate_ODC " Theft of Private Cars, police recorded offences per 10,000 of population [ODC]"


label var indep_RCS "State is independent on Dec. 31 of observed year [RCS]"
label var relmajid_RCS "ID code of religion of majority of population [RCS]"
label var chrpop_RCS "Population of Christians [RCS]"
label var chrpct_RCS "Percentage of Christians [RCS]"
label var jewpop_RCS "Population of Jews [RCS]"          
label var jewpct_RCS "Percentage of Jews [RCS]"             
label var muspop_RCS "Population of Muslims [RCS]"
label var muspct_RCS "Percentage of Muslims [RCS]"
label var hinpop_RCS " Population of Hindus (Insufficient data or numbers to subdivide) [RCS]"
label var hinpct_RCS "Percentage of Hindus [RCS]"  
label var budpop_RCS "Population of Buddhists (all branches and schools of Buddhism combined) [RCS]" 
label var budpct_RCS "Percentage of Buddhists [RCS]"
label var eacomppp_RCS "Population of East Asian Religious Complex [RCS]"
label var eacomppt_RCS "Percentage of East Asian Religious Complex [RCS]"
label var shipop_RCS "Population of Shintoists (insufficient data or numbers to subdivided) [RCS]"
label var shipct_RCS "Percentage of Shintoists [RCS]"
label var cnfpop_RCS "Population of Confucianists (insufficient data or numbers to subdivide) [RCS]" 
label var cnfpct_RCS "Percentage of Confucianists [RCS]"
label var taopop_RCS "Population of Taoists (insufficient data or numbers to subdivide) [RCS]" 
label var taopct_RCS "Percentage of Taoists [RCS]"
label var indpop_RCS "Population of Indigenous Religionists [RCS]"
label var indpct_RCS "Percentage of Indigenous Religionists [RCS]"
label var notrelpp_RCS "Population of Not Religious [RCS]"
label var notrelpt_RCS "Percentage of Not Religious [RCS]"
label var unkpop_RCS "Population of Unknown [RCS]"
label var unkpct_RCS "Percentage of Unknown [RCS]" 


label var EmigrantStock_EMS "Total emmigrant stock from [UN]"


label var archipelago_AP "At least two islands"
label var lnislands_AP "Number of islands (ppl > 100000) logged [Archipelagos]"
label var archipelago_AP "At least two islands"
label var comments_AP "List of the islands in each country"
label var numislands_AP "Number of Islands (ppl > 100000)"

order gwno country year


saveold "$mainfolder/Graham_Tucker_IPE_2_0.dta", replace version(12)



drop if year < 1975
drop if year > 2016


saveold "$mainfolder/Graham_Tucker_IPE_2_0_1975-2016.dta", replace version(12)


keep gwno country year ccode ifscode ifs gwabbrev *_EF *_FH  *_TR *_MC *_SI *_CV *_BH *_CIM *_BCG *_FS *_LY /*
*/ *_LX *_WB *_IB *_FW *_UNCTAD *_OFS *_OFI *_OPE *_TH *_AE *_PW *_WDI *_WDI_PW *_OECD *_ILO *_LI *_BZ *_GFD *_MFN
saveold "$mainfolder/Graham_Tucker_IPE_v2_0_1975-2016_Economic.dta", replace version(12)



use "$mainfolder/Graham_Tucker_IPE_2_0_1975-2016.dta", clear
keep gwno country year ccode ifscode ifs gwabbrev *_DD *_P4 *_VDEM *_DPI *_GE *_BX *_DE *_IDC *_LS *_JCB *_WGI /*
*/ *_SFI *_SGI *_WJP *_BTI *_IDA *_CR *_FA *_MU *_FP *_FHP *_HR *_TI *_PV *_PVE *_MP *_PF *_PTS *_SVS *_PO /*
*/ *_BD *_UBD *_AO *_IP *_ZH *_WE *_BIT *_MEM 
saveold "$mainfolder/Graham_Tucker_IPE_2_0_1975-2016_Political.dta", replace version(12)

use "$mainfolder/Graham_Tucker_IPE_2_0_1975-2016.dta", clear
keep gwno country year ccode ifscode ifs gwabbrev *_BL *_PIS *_ES *_EP *_ODC *_LANG *_RCS *_EMS *_AP *_EMS *_AP /*
*/ *_CE 
saveold "$mainfolder/Graham_Tucker_IPE_2_0_1975-2016_SocialGeographic.dta", replace version(12)
