---
title: "04_FullData"
author: J Andres Gannon, Erik Gartzke, and Jon Lindsay, Center for Peace and Security
  Studies (cPASS)
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '5'
  html_notebook:
    fig_height: 8
    fig_width: 12
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(magrittr)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```

# Load
```{r}
df <- readRDS(paste0(here::here(), '/data/grayzone_aggregate_new.rds'))
```

# Clean
Drop columns that describe the coding process. This table shows a list of the 60 unique target-years in the data. It drops 22 cases that are repeat Russian interventions with the same target-year.
```{r}
# Subset
df <- df %>% dplyr::select(dplyr::starts_with("resp_"), target, year_start) %>%
    dplyr::rename(year = year_start)

# Figure out how to deal with multiple observations within a country-year
df %>% dplyr::select(target, year) %>%
  dplyr::distinct() %>%
  DT::datatable()
```

# Add variables
```{r}
# COW codes
df$ccode1 <- countrycode::countrycode(df$target, "country.name", "cown")
df$ccode2 <- 365

# Distance from the US and Russia
df_dist <- read.table(paste0(here::here(), '/inst/extdata/distance.txt'), header = TRUE)

df <- dplyr::left_join(df, df_dist)

# CINC scores


# Polity


# Recent civil war


# Nuclear status


# GDP

```
