---
title: "04_FullData"
author: J Andres Gannon, Erik Gartzke, Jon Lindsay, and Peter Schram, Center for Peace and Security
  Studies (cPASS)
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    code_download: true
    toc: yes
  html_notebook:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(magrittr)
library(ggplot2)
```

# Load data
Load the newly created data with all relevant covariates
```{r}
df <- readRDS(paste0(here::here(), '/data/grayzone_model.rds'))
```

# Data summary
Basic summary statistics of the data and what it includes
```{r}
DT::datatable(df)
funModeling::plot_num(df)

hist(df$intensity)

df %>%
  dplyr::select(intensity, capdistkm_us:gdp2) %>%
  GGally::ggpairs()
```

# Model 1 - Linear Regression with state-clustered standard errors
```{r}
# OLS with standard errors clustered by country
m1 <- miceadds::lm.cluster(formula = 
                              intensity ~ 
                              capdistkm_us + 
                              capdistkm_rus +
                              NATOmem_MEM +
                              cinc_ratio +
                              polity1 +
                              civilwar +
                              nuclear1 +
                              gdp1,
                            data = df,
                            cluster = "ccode1")

coef(m1)
vcov(m1)
summary(m1)
```

Regression table of results
```{r}
texreg::texreg(
  list(m1),
  custom.model.names = c(
    "All Controls"
  ),
  custom.coef.names = c(
    "Intercept", "Distance from DC", "Distance from Moscow", "NATO membership", "CINC ratio", "Polity Score", "Civil War", "Nuclear power", "GDP"),
  digits = 3,
  ci.force = TRUE,
  ci.force.level = 0.95,
  file = "../paper/model.tex"
)
```

Regression plot
```{r, eval = FALSE}
dw1 <- dotwhisker::dwplot(m1, dot_args = list(size = 2.5),
    whisker_args = list(size = 1.5), 
    color = "black") %>%
    relabel_predictors(c(
       capdistkm_us = "Distance from DC",
       capdistkm_rus = "Distance from Moscow",
       NATOmem_MEM = "NATO membership",
       cinc_ratio = "CINC ratio",
       polity1 = "Polity score",
       civilwar = "Civil war",
       nuclear1 = "Nuclear power",
       gdp1 = "GDP"
        )) +
    geom_vline(xintercept = 0) +
    ggtitle("Coefficient Estimates") +
        theme(plot.title = element_text(face="bold", hjust = -0.0),
        legend.justification=c(0, 0), legend.position=c(0, 0),
        legend.title = element_blank()) +
    scale_colour_discrete(breaks=c(
      "Model 1"
      ),
        labels = c(
        "All Controls")) +
    labs(x = "Intensity of Russian Intervention") + 
    theme_bw() +
    theme(text = element_text(size = 24),
        axis.text.x = element_text(colour="black"), 
        axis.text.y = element_text(colour="black"),
        legend.position = c(0.8, 0.01),
        legend.justification = c(0, 0), 
        legend.background = element_rect(colour="grey80"),
        legend.title = element_blank())
```

# Model 2 - MLE with ordered probit using state-clustered standard errors
```{r}
m2 <- oglmx::oglmx(intensity ~ 
                     capdistkm_us + 
                     capdistkm_rus +
                     NATOmem_MEM +
                     cinc_ratio +
                     polity1 +
                     civilwar +
                     nuclear1 +
                     gdp1,
                   data = df,
                   link = "probit",
                   constantMEAN = FALSE,
                   constantSD = FALSE,
                   delta = 0)

summary(m2)

oglmx::margins.oglmx(m2,
                     ascontinuous = TRUE)
```
